### ISSUE TITLE
Errors on script due to out-of-date python code

### ISSUE THREAD

**Issue by minasgadalla** [mattbierner/DreamScrape#1]
Because the scraper was written more than 5 years ago, it is expected to contain some errors. When running the scraper in Python v3.9.7, you will encounter the following two errors, which are easily fixed:

**Error: " 'dict' object has no attribute 'iteritems' "**

To fix this issue in the for loop change `.iteritems():` to` .items():` like so:
`for dreamer, desc in DREAMERS.items():`

**TypeError: can't use a string pattern on a bytes-like object** 

This error occurs from the `process_dream_span` function.  Because the text variable is passed to the re expression as a byte class, it must be decoded, and simply decoding the variable resolves the error:
```
def process_dream_span(span):
    text = span.text.encode('utf-8').strip()
    text = text.decode("utf-8")  <--- decode
...
```

The scraper is extremely helpful and with the above changes it works perfectly with the 2022 version of dreambank.net. Thanks a lot for sharing your code!

**Comment by mattbierner** [comment]
Thanks for looking into this and glad you found the script useful!

Would you like to submit a PR with this fix to help out others?

**Comment by minasgadalla** [comment]
For those of you who have observed the same bad behavior, here is something that will probably save you time.

First of all, Lightsail is not meant to be used for production websites but rather for development websites. So if you are using Lightsail, consider moving to EC2.

Secondly, as most WordPress websites are dependent on many plugins over which we have no control and can execute stuff in a non-optimized way, I recommend changing the `pm.type` to `static` and finding the setting `pm.max_children`  by dividing the RAM you want to allocate by the average php-fpm usage memory.

After those changes you should monitor the CPU, RAM, avg php-fpm ram usage,  and notice if you have any memory leaks

[GH-247](https://github.com/bitnami/vms/issues/248)

**Comment by minasgadalla** [comment]
Here's something that will likely save you time if you've witnessed the same behavior on your bitanmi wordpress application. 

First of all, Lightsail is not intended to be used for production websites but rather for development websites. So if you are using Lightsail, consider moving to EC2.

Secondly, as most WordPress websites are dependent on many plugins over which we have no control and can execute stuff in a non-optimized way, I recommend changing the `pm.type` to `static` and finding the appropriate number for `pm.max_children`  by dividing the RAM you want to allocate by the average php-fpm usage memory.

After those changes you should monitor the CPU, RAM, avg php-fpm ram usage, and notice if you have any memory leaks

https://github.com/bitnami/vms/issues/248
